apiVersion: network.kkohtaka.org/v1alpha1
kind: DNSRecord
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: dnsrecord-sample
spec:
  domain: www.example.com
  a:
    - 192.0.2.1
    - 192.0.2.2
    - 192.0.2.3
